title: International Press book series SDG author support
description: TeX related material for the manuscript preparation for the 
             International Press book series Surveys in Differential Geometry 
             (SDG)
show_downloads: true
theme: jekyll-theme-tactile
